// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simple.proto

/*
Package simple_proto is a generated protocol buffer package.

It is generated from these files:
	simple.proto

It has these top-level messages:
	LongMessage
	ShortMessage2
*/
package simple_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import tutorial "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enum outside the Long Enum
type Enum2 int32

const (
	Enum2_ZERO Enum2 = 0
	Enum2_ONE  Enum2 = 1
)

var Enum2_name = map[int32]string{
	0: "ZERO",
	1: "ONE",
}
var Enum2_value = map[string]int32{
	"ZERO": 0,
	"ONE":  1,
}

func (x Enum2) String() string {
	return proto.EnumName(Enum2_name, int32(x))
}
func (Enum2) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LongMessage_Enum1 int32

const (
	LongMessage_ZERO LongMessage_Enum1 = 0
	LongMessage_ONE  LongMessage_Enum1 = 1
)

var LongMessage_Enum1_name = map[int32]string{
	0: "ZERO",
	1: "ONE",
}
var LongMessage_Enum1_value = map[string]int32{
	"ZERO": 0,
	"ONE":  1,
}

func (x LongMessage_Enum1) String() string {
	return proto.EnumName(LongMessage_Enum1_name, int32(x))
}
func (LongMessage_Enum1) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type LongMessage struct {
	Name     string                       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Int_32   int32                        `protobuf:"varint,2,opt,name=int_32,json=int32" json:"int_32,omitempty"`
	Int_64   int64                        `protobuf:"varint,3,opt,name=int_64,json=int64" json:"int_64,omitempty"`
	Uint_32  uint32                       `protobuf:"varint,4,opt,name=uint_32,json=uint32" json:"uint_32,omitempty"`
	Uint_64  uint64                       `protobuf:"varint,5,opt,name=uint_64,json=uint64" json:"uint_64,omitempty"`
	Fixed_32 uint32                       `protobuf:"fixed32,6,opt,name=fixed_32,json=fixed32" json:"fixed_32,omitempty"`
	Fixed_64 uint64                       `protobuf:"fixed64,7,opt,name=fixed_64,json=fixed64" json:"fixed_64,omitempty"`
	Short1   []*LongMessage_ShortMessage1 `protobuf:"bytes,8,rep,name=short1" json:"short1,omitempty"`
	Short2   []*ShortMessage2             `protobuf:"bytes,9,rep,name=short2" json:"short2,omitempty"`
	E1       LongMessage_Enum1            `protobuf:"varint,10,opt,name=e1,enum=simple.proto.LongMessage_Enum1" json:"e1,omitempty"`
	E2       Enum2                        `protobuf:"varint,11,opt,name=e2,enum=simple.proto.Enum2" json:"e2,omitempty"`
	Person   *tutorial.Person             `protobuf:"bytes,12,opt,name=person" json:"person,omitempty"`
}

func (m *LongMessage) Reset()                    { *m = LongMessage{} }
func (m *LongMessage) String() string            { return proto.CompactTextString(m) }
func (*LongMessage) ProtoMessage()               {}
func (*LongMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LongMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LongMessage) GetInt_32() int32 {
	if m != nil {
		return m.Int_32
	}
	return 0
}

func (m *LongMessage) GetInt_64() int64 {
	if m != nil {
		return m.Int_64
	}
	return 0
}

func (m *LongMessage) GetUint_32() uint32 {
	if m != nil {
		return m.Uint_32
	}
	return 0
}

func (m *LongMessage) GetUint_64() uint64 {
	if m != nil {
		return m.Uint_64
	}
	return 0
}

func (m *LongMessage) GetFixed_32() uint32 {
	if m != nil {
		return m.Fixed_32
	}
	return 0
}

func (m *LongMessage) GetFixed_64() uint64 {
	if m != nil {
		return m.Fixed_64
	}
	return 0
}

func (m *LongMessage) GetShort1() []*LongMessage_ShortMessage1 {
	if m != nil {
		return m.Short1
	}
	return nil
}

func (m *LongMessage) GetShort2() []*ShortMessage2 {
	if m != nil {
		return m.Short2
	}
	return nil
}

func (m *LongMessage) GetE1() LongMessage_Enum1 {
	if m != nil {
		return m.E1
	}
	return LongMessage_ZERO
}

func (m *LongMessage) GetE2() Enum2 {
	if m != nil {
		return m.E2
	}
	return Enum2_ZERO
}

func (m *LongMessage) GetPerson() *tutorial.Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type LongMessage_ShortMessage1 struct {
	Name string `protobuf:"bytes,16,opt,name=name" json:"name,omitempty"`
}

func (m *LongMessage_ShortMessage1) Reset()                    { *m = LongMessage_ShortMessage1{} }
func (m *LongMessage_ShortMessage1) String() string            { return proto.CompactTextString(m) }
func (*LongMessage_ShortMessage1) ProtoMessage()               {}
func (*LongMessage_ShortMessage1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *LongMessage_ShortMessage1) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// message outside the LongMessage
type ShortMessage2 struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ShortMessage2) Reset()                    { *m = ShortMessage2{} }
func (m *ShortMessage2) String() string            { return proto.CompactTextString(m) }
func (*ShortMessage2) ProtoMessage()               {}
func (*ShortMessage2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ShortMessage2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*LongMessage)(nil), "simple.proto.LongMessage")
	proto.RegisterType((*LongMessage_ShortMessage1)(nil), "simple.proto.LongMessage.ShortMessage1")
	proto.RegisterType((*ShortMessage2)(nil), "simple.proto.ShortMessage2")
	proto.RegisterEnum("simple.proto.Enum2", Enum2_name, Enum2_value)
	proto.RegisterEnum("simple.proto.LongMessage_Enum1", LongMessage_Enum1_name, LongMessage_Enum1_value)
}

func init() { proto.RegisterFile("simple.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcb, 0x8e, 0xd3, 0x30,
	0x14, 0xc5, 0x79, 0xb6, 0x37, 0x33, 0x28, 0x18, 0x21, 0x3c, 0x61, 0x81, 0xd5, 0x59, 0x60, 0xb1,
	0x08, 0x8a, 0x13, 0x65, 0x8b, 0x84, 0xd4, 0x1d, 0x9d, 0x22, 0xcf, 0x8e, 0x0d, 0x4a, 0x89, 0x69,
	0x23, 0xda, 0xb8, 0xca, 0x03, 0xc1, 0x4f, 0xf3, 0x0d, 0x28, 0xae, 0x4b, 0x9b, 0x51, 0xbb, 0xcb,
	0x3d, 0xaf, 0xf8, 0xfa, 0x18, 0x6e, 0xda, 0x6a, 0xb7, 0xdf, 0xca, 0x78, 0xdf, 0xa8, 0x4e, 0xe1,
	0xd1, 0x14, 0xbd, 0x28, 0xca, 0xb2, 0x91, 0x6d, 0xbb, 0x52, 0xea, 0xe7, 0x01, 0x9a, 0xfd, 0xb5,
	0x21, 0xf8, 0xac, 0xea, 0xf5, 0x42, 0xb6, 0x6d, 0xb1, 0x96, 0x18, 0x83, 0x53, 0x17, 0x3b, 0x49,
	0x10, 0x45, 0x6c, 0x2a, 0xf4, 0x37, 0x7e, 0x05, 0x5e, 0x55, 0x77, 0xdf, 0x52, 0x4e, 0x2c, 0x8a,
	0x98, 0x2b, 0xdc, 0xaa, 0xee, 0x52, 0x7e, 0x84, 0xf3, 0x8c, 0xd8, 0x14, 0x31, 0x5b, 0xc3, 0x79,
	0x86, 0x5f, 0x83, 0xdf, 0x1b, 0xb9, 0x43, 0x11, 0xbb, 0x15, 0x5e, 0x7f, 0xd0, 0x1f, 0x89, 0x3c,
	0x23, 0x2e, 0x45, 0xcc, 0x39, 0x10, 0x79, 0x86, 0xef, 0x60, 0xf2, 0xa3, 0xfa, 0x2d, 0xcb, 0xc1,
	0xe2, 0x51, 0xc4, 0x7c, 0xe1, 0xeb, 0x39, 0xe5, 0x27, 0x2a, 0xcf, 0x88, 0x4f, 0x11, 0xf3, 0x0c,
	0x95, 0x67, 0xf8, 0x23, 0x78, 0xed, 0x46, 0x35, 0x5d, 0x42, 0x26, 0xd4, 0x66, 0x01, 0x7f, 0x17,
	0x9f, 0xef, 0x1a, 0x9f, 0x2d, 0x15, 0x3f, 0x0e, 0x3a, 0x33, 0x24, 0xc2, 0xd8, 0x70, 0x6a, 0x02,
	0x38, 0x99, 0xea, 0x80, 0x37, 0xe3, 0x80, 0x73, 0x13, 0x37, 0x26, 0x8e, 0x3f, 0x80, 0x25, 0x13,
	0x02, 0x14, 0xb1, 0xe7, 0xfc, 0xed, 0xf5, 0x3f, 0xce, 0xeb, 0x7e, 0x97, 0x08, 0x4b, 0x26, 0xf8,
	0x1e, 0x2c, 0xc9, 0x49, 0xa0, 0x0d, 0x2f, 0xc7, 0x86, 0x41, 0xc4, 0x85, 0x25, 0x39, 0x66, 0xe0,
	0xed, 0x65, 0xd3, 0xaa, 0x9a, 0xdc, 0x50, 0xc4, 0x02, 0x1e, 0xc6, 0x5d, 0xdf, 0xa9, 0xa6, 0x2a,
	0xb6, 0xf1, 0x17, 0x8d, 0x0b, 0xc3, 0x47, 0xf7, 0x70, 0x3b, 0xda, 0xe6, 0x7f, 0x61, 0xe1, 0xa9,
	0xb0, 0x59, 0x04, 0xae, 0x3e, 0x00, 0x9e, 0x80, 0xf3, 0x75, 0x2e, 0x96, 0xe1, 0x33, 0xec, 0x83,
	0xbd, 0x7c, 0x98, 0x87, 0x68, 0xf6, 0x24, 0x80, 0x5f, 0x6a, 0xfc, 0xbd, 0x09, 0xe0, 0x17, 0x02,
	0xf8, 0x12, 0xa6, 0x8b, 0x3f, 0x8f, 0xb2, 0xf9, 0x55, 0x7d, 0x97, 0xf8, 0x13, 0xc0, 0x42, 0x76,
	0x1b, 0x55, 0x3e, 0x0c, 0x0f, 0xe5, 0xee, 0xea, 0x85, 0x44, 0xd7, 0xa9, 0x95, 0xa7, 0xa1, 0xf4,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x07, 0x85, 0x77, 0xba, 0x02, 0x00, 0x00,
}
